services:
  postgres:
    container_name: postgres_container
    image: postgres:14.1
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      APP_DB_USER: docker
      APP_DB_PASS: docker
      APP_DB_NAME: photo_sharing_service
    ports:
      - 5432:5432